services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: e_com_backend_prod
    environment:
      - NODE_ENV=production
      - PORT=4005
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ACCESS_TOKEN_EXP=${ACCESS_TOKEN_EXP}
      - REFRESH_TOKEN_EXP=${REFRESH_TOKEN_EXP}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - REDIS_URL=${REDIS_URL_PROD}
      - DATABASE_URL=${DATABASE_URL_PROD}
      - DIRECT_URL=${DIRECT_URL_PROD}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod-migration-runner
    environment:
      - DATABASE_URL=${DATABASE_URL_PROD}
