packages:
  - 'apps/*'

minimumReleaseAge: 0

minimumReleaseAgeExclude:
  - '@next/*'
  - next

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  bcrypt: true
  prisma: true
  unrs-resolver: true
